# Generated by Django 3.2.11 on 2022-01-16 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tut_name', models.CharField(max_length=200)),
                ('tut_link', models.CharField(max_length=200)),
                ('tut_format', models.CharField(choices=[('written', 'written'), ('video', 'video')], default='written', max_length=20)),
                ('tut_tag', models.CharField(max_length=200)),
                ('tut_updated', models.DateField()),
                ('tut_difficulty', models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], default='beginner', max_length=20)),
                ('tut_time', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='space.category')),
            ],
            options={
                'verbose_name_plural': 'Tutorials',
                'ordering': ('-created_at',),
            },
        ),
    ]
