# Generated by Django 3.2.11 on 2022-04-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='tut_difficulty',
            new_name='difficulty',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='tut_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='tut_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='tut_link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
