# Generated by Django 3.2.11 on 2022-04-04 08:27

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('space', '0002_auto_20220404_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='tut_tag',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
